### ISSUE TITLE
replicationfactor and writeconcern missing for create database?

### ISSUE THREAD

**Issue by oliverhausler** [deusdat/arangomigo#13]
It seems `replicationfactor` and `writeconcern` fields cannot be set. At least they are not documented.

```
type: database
action: create
name: attach
allowed:
  - username: ${user}
    password: ${password}
replicationfactor: 3 <-- seems missing
writeconcern: 2 <-- seems missing
```

![Screen Shot 2020-03-25 at 09 32 59](https://user-images.githubusercontent.com/8090341/77542023-f180bc00-6e7b-11ea-85a2-3d4a8be107f8.png)
